version: "3.2"

services:
  web:
    build: web
    ports:
      - 8080:80
    volumes:
      - ./web/static/:/usr/share/nginx/html/

  tiles:
    image: klokantech/tileserver-gl
    ports:
      - 8081:80
    volumes:
      - ./data:/data

  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./data:/data
    ports:
      - 5000:5000
    command: osrm-routed --algorithm mld /data/paris.osrm
